import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./layouts/Navbar";
import dynamic from "next/dynamic";
// import ProLayout from "./layouts/ProLayout";

const inter = Inter({ subsets: ["latin"] });

const Headbar = dynamic(() => import("./layouts/Headbar"), { ssr: false });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar children={children} /> */}
        <Headbar children={children} />
      </body>
    </html>
  );
}
